# Generated by Django 4.1.7 on 2023-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_products_dislikes_alter_products_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
