# Generated by Django 4.1.7 on 2023-03-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_products_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
